/* Generated by gbrecomp */
#ifndef super_mario_land_H
#define super_mario_land_H

#include "gbrt.h"

const GBConfig* super_mario_land_default_config(void);
void super_mario_land_run(GBContext* ctx);
void super_mario_land_init(GBContext* ctx, const uint8_t* rom_data, size_t rom_size);
int super_mario_land_main(int argc, char* argv[]);

#endif
